apiVersion: apps/v1
kind: Deployment
metadata:
  name: simfrontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simfrontend
  template:
    metadata:
      labels:
        app: simfrontend
    spec:
      containers:
      - name: simfrontend
        image: eleni88/simulation-front:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"    
        ports:
        - containerPort: 80